In [32]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [ ]:
import scipy.spatial.distance as d

## Compare Distance Metrics
Goal is to define a distance which is smaller the more 1's two vectors have in common.
* For example if two customers choose the same items that would bring them closer.

In [ ]:
center = np.array([[1, 0, 1]])
customers = np.array([
        [1, 0, 1],
        [1, 1, 1],
        [0, 0, 1],
    ])

In [36]:
X = np.append(center, customers, axis=0)

### euclidian

* distance from center for every customer is in the first customer.len rows

In [38]:
dist_euclidean = d.pdist(X, metric='euclidean')
dist_center[0:len(customers)]

array([ 0.,  1.,  1.])

### manhattan

In [39]:
dist_manhattan = d.pdist(X, metric='cityblock')
dist_manhattan[0:len(customers)]

array([ 0.,  1.,  1.])

### cosine

* cosine distance does the trick.

In [40]:
dist_cosine = d.pdist(X, metric='cosine')
dist_cosine[0:len(customers)]

array([  2.22044605e-16,   1.83503419e-01,   2.92893219e-01])

In [14]:
import numpy as np
import scipy
import pandas as pd

In [15]:
import scipy.spatial.distance as distance

## Distance

In [16]:
n = np.array([[0,1,0,1],
              [0,0,1,1]])
m = np.array([1,2,3,4])
d = n*m
d

array([[0, 2, 0, 4],
       [0, 0, 3, 4]])

In [17]:
np.array([0,1,0,0,1]).dot(np.array([1,2,3,4,5]) * -1)

-7

In [18]:
np.dot([0,1,0,0,1], np.array([1,2,3,4,5]) * -1)

-7

In [19]:
[1,2,3,4,5] * -1

[]

In [20]:
np.array([0,-2,0,-4])

array([ 0, -2,  0, -4])

In [21]:
a = np.array([[0, 2, 0, 4],
              [0, 0, 3, 4],
              [1, 2, 0, 2]])

In [22]:
np.transpose(np.nonzero(a))

array([[0, 1],
       [0, 3],
       [1, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 3]])

find row with the highest overall score

In [23]:
a = np.array([[0, 2, 0, 4],
              [0, 0, 3, 4],
              [1, 2, 0, 2]])

expected [0, 0, 3, 4]

In [24]:
np.amax(a, axis=0)

array([1, 2, 3, 4])

as expected

In [25]:
np.amax([[0,0,0,0], [0,1,0,1], [1,1,1,1], [2,1,1,1]], axis=0)

array([2, 1, 1, 1])

what is the index value of the row with the highest overall score?

#### Chebyshev Distance
* max absolute difference between two elements
* in which feature the two disagree the most

In [26]:
distance.chebyshev([0,1], [1,4])

3

In [27]:
distance.chebyshev([0,1], [7,4])

7

#### Minkowski Distance
* 

In [28]:
distance.minkowski([0,1,0,0,1], [1,2,3,4,5], p=1)

13

#### Manhattan Distance
* 

#### Cosine Distance
* 