first get the packages we gonna use.
print the version for all of them.

In [52]:
%pylab inline

import pandas as pd
import numpy as np
import scipy as sp
from scipy import stats

Populating the interactive namespace from numpy and matplotlib


#### index, slice: extract columns and rows

In [53]:
data = np.array([1, 2, 4, -3, -4, -1, 5, 8, 10]).reshape(3,3)
data

array([[ 1,  2,  4],
       [-3, -4, -1],
       [ 5,  8, 10]])

get a single row by index

In [54]:
data[1]

array([-3, -4, -1])

In [61]:
data[:,1:]

array([[ 2,  4],
       [-4, -1],
       [ 8, 10]])

below example I would expect
<code>
[[-1],
 [10]]
</code>
when operation is defined as sub-matrix extraction

In [62]:
data[1:,2]

array([-1, 10])

result is 1-dim. chooses the smallest dim as dim of result.

In [79]:
data[1:,2].ndim

1

(2,) != (2,0)
dim is always > 0

In [78]:
expected = np.array([[-1],
                     [10]])
got = np.array([-1, 10])

print expected.shape
print got.shape

(2, 1)
(2,)


slice is a sub-matrix. smallest shape is (2,2), smallest dim 2

In [73]:
data[1:,1:]

array([[-4, -1],
       [ 8, 10]])

In [80]:
data[1:,1:].shape

(2, 2)

ignores the '-' in front of the zero. negative index must be > 0.

In [81]:
data[-0]

array([1, 2, 4])

get last row by index.

In [82]:
data[-1]

array([ 5,  8, 10])

sub-matrix as the last 2 rows, last 2 columns.

In [83]:
data[-2:,-2:]

array([[-4, -1],
       [ 8, 10]])

#### merge

In [71]:
a = np.array([[0, 1], [1, 2]])
b = np.array([3, 3])
np.concatenate(a, b)

TypeError: only length-1 arrays can be converted to Python scalars

#### filter

Slice, Split

Training Data and Prediction Data

In [57]:
d = [3, 4, 5, 8]
print d[:-1]
print d[-1:]

[3, 4, 5]
[8]


#### Remove 95-percentile

Concat

Group By