first get the packages we gonna use.
print the version for all of them.

In [52]:
%pylab inline

import pandas as pd
import numpy as np
import scipy as sp
from scipy import stats

Populating the interactive namespace from numpy and matplotlib


#### extract columns and rows

In [53]:
data = np.array([1, 2, 4, -3, -4, -1, 5, 8, 10]).reshape(3,3)
data

array([[ 1,  2,  4],
       [-3, -4, -1],
       [ 5,  8, 10]])

In [54]:
data[1]

array([-3, -4, -1])

In [61]:
data[:,1:]

array([[ 2,  4],
       [-4, -1],
       [ 8, 10]])

would expect
<code>
[[-1],
 [10]]
</code>

In [62]:
data[1:,2]

array([-1, 10])

In [78]:
expected = np.array([[-1],
                     [10]])
got = np.array([-1, 10])

print expected.shape
print got.shape

(2, 1)
(2,)


slice is a sub-matrix

In [73]:
data[1:,1:]

array([[-4, -1],
       [ 8, 10]])

#### merge

In [71]:
a = np.array([[0, 1], [1, 2]])
b = np.array([3, 3])
np.concatenate(a, b)

TypeError: only length-1 arrays can be converted to Python scalars

#### filter

Slice, Split

Training Data and Prediction Data

In [57]:
d = [3, 4, 5, 8]
print d[:-1]
print d[-1:]

[3, 4, 5]
[8]


#### Remove 95-percentile

Concat

Group By