In [32]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


### Compare Distance Metrics
Goal is to define a distance which is smaller the more 1's two vectors have in common.
For example if two customers choose the same items that would bring them closer.

In [ ]:
center = np.array([[1, 0, 1]])
customers = np.array([
        [1, 0, 1],
        [1, 1, 1],
        [0, 0, 1],
    ])

In [36]:
import scipy.spatial.distance as d

X = np.append(center, customers, axis=0)

distance from center for every customer is in the first customer.len rows

In [38]:
dist_euclidean = d.pdist(X, metric='euclidean')
dist_center[0:len(customers)]

array([ 0.,  1.,  1.])

In [39]:
dist_manhattan = d.pdist(X, metric='cityblock')
dist_manhattan[0:len(customers)]

array([ 0.,  1.,  1.])

cosine distance does the trick.

In [40]:
dist_cosine = d.pdist(X, metric='cosine')
dist_cosine[0:len(customers)]

array([  2.22044605e-16,   1.83503419e-01,   2.92893219e-01])