In [41]:
import numpy as np
import scipy as sc
import sympy as sy

### Problems 4.4

#### No 1

In [42]:
x = np.array([1, 3, 7, 9, 14, 16])
px = np.array([sy.Rational(3,80), sy.Rational(27,80), sy.Rational(11,80),
               sy.Rational(17,80), sy.Rational(13,80), sy.Rational(9,80)])
px

array([3/80, 27/80, 11/80, 17/80, 13/80, 9/80], dtype=object)

use vector operations

In [43]:
mu = (x*px).sum()
mu

8

In [44]:
x.dot(px)

8

In [45]:
mu_v = np.array([mu] * len(x))
mu_v

array([8, 8, 8, 8, 8, 8], dtype=object)

In [46]:
x - mu_v

array([-7, -5, -1, 1, 6, 8], dtype=object)

In [50]:
(x - mu_v) ** 2

array([49, 25, 1, 1, 36, 64], dtype=object)

In [52]:
sum(((x - mu_v) ** 2) * px)

947/40

In [59]:
sqrt(float(sy.Rational(947/40)))

4.7958315233127191

In [70]:
for ix, v in enumerate(x):
    print px[ix].p

3
27
11
17
13
9


#### No 2