In [75]:
import numpy as np
import scipy as sc
import sympy as sy
import pandas as pd

### Problems 4.4

#### No 1

In [42]:
x = np.array([1, 3, 7, 9, 14, 16])
px = np.array([sy.Rational(3,80), sy.Rational(27,80), sy.Rational(11,80),
               sy.Rational(17,80), sy.Rational(13,80), sy.Rational(9,80)])
px

array([3/80, 27/80, 11/80, 17/80, 13/80, 9/80], dtype=object)

use vector operations

In [43]:
mu = (x*px).sum()
mu

8

In [44]:
x.dot(px)

8

In [45]:
mu_v = np.array([mu] * len(x))
mu_v

array([8, 8, 8, 8, 8, 8], dtype=object)

In [46]:
x - mu_v

array([-7, -5, -1, 1, 6, 8], dtype=object)

In [50]:
(x - mu_v) ** 2

array([49, 25, 1, 1, 36, 64], dtype=object)

In [52]:
sum(((x - mu_v) ** 2) * px)

947/40

In [96]:
sqrt(947/40.0)

4.8656962502811458

create the distribution data from the proportions given

In [80]:
x_dist = []
for ix, v in enumerate(x):
    x_dist += [v] * px[ix].p

x_dist = np.array(x_dist)
unique, counts = np.unique(x_dist, return_counts=True)
np.asarray((unique, counts)).T

array([[ 1,  3],
       [ 3, 27],
       [ 7, 11],
       [ 9, 17],
       [14, 13],
       [16,  9]])

In [87]:
x_dist.std()

4.8656962502811458

In [86]:
x_dist.mean()

8.0

In [83]:
from scipy import stats
stats.describe(x_dist)

DescribeResult(nobs=80, minmax=(1, 16), mean=8.0, variance=23.974683544303797, skewness=0.32748715241146104, kurtosis=-1.2645580051047658)

#### No 2