### setup

In [4]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [5]:
from sympy import *
init_printing(use_unicode=True)

In [18]:
x, y, z = symbols('x y z')
h = symbols('h')
n, m = symbols('n m')

### a few difference quotient of monomials

In [29]:
dq_mono = [((n+1)**i - n**i) for i in range(2,6)]
dq_mono

#### 

In [36]:
dq_mono_sample = [[dq.subs(n, i) for i in range(0,6)] for dq in dq_mono]
dq_mono_sample

#### 

In [38]:
dq_mono_diff = [np.diff(sample) for sample in dq_mono_sample]
dq_mono_diff

[array([2, 2, 2, 2, 2], dtype=object),
 array([6, 12, 18, 24, 30], dtype=object),
 array([14, 50, 110, 194, 302], dtype=object),
 array([30, 180, 570, 1320, 2550], dtype=object)]

In [39]:
dq_mono_second_diff = [np.diff(sample) for sample in dq_mono_diff]
dq_mono_second_diff

[array([0, 0, 0, 0], dtype=object),
 array([6, 6, 6, 6], dtype=object),
 array([36, 60, 84, 108], dtype=object),
 array([150, 390, 750, 1230], dtype=object)]

In [40]:
dq_mono_third_diff = [np.diff(sample) for sample in dq_mono_second_diff]
dq_mono_third_diff

[array([0, 0, 0], dtype=object),
 array([0, 0, 0], dtype=object),
 array([24, 24, 24], dtype=object),
 array([240, 360, 480], dtype=object)]